/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface UrlOpenRequest {
  url: string
}

export interface UrlOpenResponse {
  accepted: boolean
}

export interface AbilityInitContext {
  basePath?: string
  prefPath?: string
  preferredLocales?: string
  moduleName?: string
}

export interface ApplicationLifecycle {
  bridgePlugins: Array<BridgePluginDeclaration>
  environmentCallback: EnvironmentCallback
  windowStageEventCallback: WindowStageEventCallback
  keyboardEventCallback: KeyboardCallback
}

/**
  * Structural declaration exported to ArkTS after the native module has configured its Rust
  * plugin registry. The host uses this to select the matching factory automatically and to
  * validate the parts of the contract that affect scheduling. Request and response ABI identity
  * remains pinned by each named N-API type.
  */
export interface BridgePluginDeclaration {
  id: string
  execution: string
  requires: Array<string>
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void
  onMemoryLevel: (arg: number) => void
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void
}

export interface NodeAcknowledgement {
  accepted: boolean
}

/** Appends the node of `child_handle` under the node of `parent_handle`. */
export interface NodeAppendChildRequest {
  parentHandle: number
  childHandle: number
}

/** Request marker for `create-container`: the response carries the new handle. */
export interface NodeCreateContainerRequest {

}

/** Detaches a handle-owned node from its parent and disposes it. */
export interface NodeDisposeRequest {
  handle: number
}

/** Opaque handle of a container `FrameNode` created in ArkTS. */
export interface NodeHandleResponse {
  handle: number
}

/** Appends a handle-owned node to this module's component root. */
export interface NodeMountIntoRootRequest {
  handle: number
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void
  onWindowStageDestroy: () => void
  onAbilityCreate: (arg: string) => void
  onAbilityDestroy: () => void
  onAbilitySaveState: () => void
  onAbilityRestoreState: () => void
  onWindowStageEvent: (arg: number) => void
  onWindowSizeChange: (arg: object) => void
  onWindowRectChange: (arg: object) => void
  onAvoidAreaChange: (arg: object) => void
}

export interface CertFileRequest {
  /** `"certificate"`, `"private_key"` or `"ca_certificate"`. */
  kind: string
}

export interface CertFileResponse {
  /** Sandbox path of the copied certificate; empty when the user cancelled. */
  path: string
}

export interface ColorModeRequest {
  /** `ConfigurationConstant.ColorMode` value pushed from native UI. */
  mode: number
}

export interface ColorModeResponse {

}

export interface ExportTextRequest {
  suggestedName: string
  content: string
}

export interface ExportTextResponse {

}

export interface VpnStartRequest {
  /** Serialized `VpnOptions` JSON for the extension Want. */
  optionsJson: string
}

export interface VpnStartResponse {

}

export interface VpnStopRequest {

}

export interface VpnStopResponse {

}

export declare function attachPlatformSharedMemory(ashmemFd: number, notificationFd: number): void

export declare function awaitPlatformVpnStart(attemptId: string): Promise<string>

export declare function awaitPlatformVpnStartAttachment(attemptId: string, timeoutMs: number): Promise<boolean>

export declare function beginPlatformVpnStart(): string

export declare function bindPlatformVpnStart(attemptId: string): void

export declare function cancelAuthChallenge(): void

/** Wake the in-process waiter parked in `wait_for_platform_change_event`. */
export declare function cancelPlatformChangeWait(): void

export declare function cancelPlatformVpnStart(attemptId: string): boolean

export declare function clearSocketProtect(): void

export declare function configureAppHome(homeDir: string): void

/**
  * VPN-extension process entry. Persistent profiles stay in the app-private
  * directory; authenticated handoff and live lifecycle state use ashmem.
  */
export declare function configureAppHomeForExtension(homeDir: string): void

export declare function configurePlatformIdentity(osFullName: string, displayVersion: string, sdkApiVersion: string, deviceType: string, appVersion: string, uniqueId: string): void

export declare function configureSystemColorMode(colorMode: number): void

export declare function configureUiLocale(locale: string): void

export declare function defaultVpnOptions(): string

export declare function disposeAllRenders(): void

/**
  * r" Releases only the matching Ability-session transport. A stale
  * r" owner cannot clear endpoints installed for a later session.
  */
export declare function disposeBridge(bridgeOwner: string): void

export declare function disposeRender(renderOwner: string): void

export declare function expirePlatformVpnStart(): boolean

export declare function failPlatformVpnStart(attemptId: string, error: string): boolean

export declare function failUnattachedPlatformVpnStart(attemptId: string, error: string): boolean

export declare function init(bindings: object, bridgeOwner: string, context?: AbilityInitContext): ApplicationLifecycle

export declare function initializePlatformSharedMemory(): string

export declare function onBackPressIntercept(): boolean

/** r" ArkTS-only lifecycle transitions, currently UI-context readiness. */
export declare function onBridgeLifecycle(kind: string): void

/**
  * r" Synchronous ArkTS platform callback -> Rust plugin decision port.
  * r"
  * r" The N-API value is scoped to this call; the returned value is
  * r" produced before ArkTS resumes the originating platform callback.
  */
export declare function onBridgeSyncEvent(pluginId: string, event: string, requestTypeName: string, responseTypeName: string, value: unknown): unknown

export declare function pendingAuthChallenge(): string

export declare function prepareVpn(): Promise<string>

/**
  * Called from the VPN-extension process only: re-auth with handoff credentials
  * and return fresh VpnOptions (addresses/DNS) before TUN create.
  */
export declare function prepareVpnInExtension(optionsJson: string): Promise<string>

export declare function querySession(): string

/**
  * Register ics-style per-fd protect: OpenConnect → `vpnConnection.protect(fd)`.
  *
  * Pass `{ protectSocket: async (fd: number) => Promise<void> }`. Native waits
  * for completion before OpenConnect calls connect(2).
  */
export declare function registerSocketProtect(callbacks: object): void

export declare function render(slot: NodeContent, renderOwner: string): void

export declare function securePrivateFile(path: string): void

export declare function setPlatformVpnFailed(error: string): void

export declare function setPlatformVpnRunning(running: boolean): void

export declare function setPlatformVpnStarting(starting: boolean): void

export declare function startVpn(fd: number, optionsJson: string): Promise<void>

export declare function stopVpn(): Promise<void>

/** Submit answers for the current OpenConnect auth challenge (multi-round MFA). */
export declare function submitAuthChallenge(replyJson: string): void

export declare function syncPlatformChanges(): void

/**
  * Block until the peer process publishes a platform frame (or the wait is
  * cancelled). Fully event driven: parks on the notification socket, never
  * polls a timeout.
  */
export declare function waitForPlatformChangeEvent(): Promise<boolean>

