/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface AbilityInitContext {
  basePath?: string
  prefPath?: string
  preferredLocales?: string
  moduleName?: string
}

export interface ApplicationLifecycle {
  environmentCallback: EnvironmentCallback
  windowStageEventCallback: WindowStageEventCallback
  keyboardEventCallback: KeyboardCallback
}

export interface DownloadStartResult {
  allow: boolean
  tempPath?: string
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void
  onMemoryLevel: (arg: number) => void
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void
}

export interface WebViewInitData {
  url?: string
  id?: string
  style?: WebViewStyle
  javascriptEnabled?: boolean
  devtools?: boolean
  userAgent?: string
  autoplay?: boolean
  initializationScripts?: Array<string>
  headers?: Record<string, string>
  html?: string
  transparent?: boolean
  onDragAndDrop?: (arg: string) => void
  onDownloadStart: OnDownloadStart
  onDownloadEnd: OnDownloadEnd
  onNavigationRequest?: (arg: string) => boolean
  onTitleChange?: (arg: string) => void
}

export interface WebViewStyle {
  x?: number | string
  y?: number | string
  visible?: boolean
  backgroundColor?: string
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void
  onWindowStageDestroy: () => void
  onAbilityCreate: () => void
  onAbilityDestroy: () => void
  onAbilitySaveState: () => void
  onAbilityRestoreState: () => void
  onWindowStageEvent: (arg: number) => void
  onWindowSizeChange: (arg: object) => void
  onWindowRectChange: (arg: object) => void
  onAvoidAreaChange: (arg: object) => void
}

export declare function attachPlatformSharedMemory(ashmemFd: number, notificationFd: number): void

export declare function awaitPlatformVpnStart(attemptId: string): Promise<string>

export declare function awaitPlatformVpnStartAttachment(attemptId: string, timeoutMs: number): Promise<boolean>

export declare function beginPlatformVpnStart(): string

export declare function bindPlatformVpnStart(attemptId: string): void

export declare function cancelAuthChallenge(): void

export declare function cancelPlatformVpnStart(attemptId: string): boolean

export declare function clearSocketProtect(): void

/**
  * Complete a document-picker request started by `pickCertFile` (ArkTS → native).
  *
  * `path` may be empty / omitted when the user cancelled the picker.
  */
export declare function completeFilePick(requestId: number, path?: string | undefined | null): void

export declare function configureAppHome(homeDir: string): void

/**
  * VPN-extension process entry. Persistent profiles stay in the app-private
  * directory; authenticated handoff and live lifecycle state use ashmem.
  */
export declare function configureAppHomeForExtension(homeDir: string): void

export declare function configurePlatformIdentity(osFullName: string, displayVersion: string, sdkApiVersion: string, deviceType: string, appVersion: string, uniqueId: string): void

export declare function configureSystemColorMode(colorMode: number): void

export declare function configureUiLocale(locale: string): void

export declare function defaultVpnOptions(): string

export declare function destroy(): void

export declare function expirePlatformVpnStart(): boolean

export declare function failPlatformVpnStart(attemptId: string, error: string): boolean

export declare function failUnattachedPlatformVpnStart(attemptId: string, error: string): boolean

export declare function init(context?: AbilityInitContext): ApplicationLifecycle

export declare function initializePlatformSharedMemory(): string

export declare function onBackPressIntercept(): boolean

export declare function pendingAuthChallenge(): string

export declare function prepareVpn(): Promise<string>

/**
  * Called from the VPN-extension process only: re-auth with handoff credentials
  * and return fresh VpnOptions (addresses/DNS) before TUN create.
  */
export declare function prepareVpnInExtension(optionsJson: string): Promise<string>

export declare function querySession(): string

export declare function registerPlatformCallbacks(callbacks: object): void

/**
  * Register ics-style per-fd protect: OpenConnect → `vpnConnection.protect(fd)`.
  *
  * Pass `{ protectSocket: async (fd: number) => Promise<void> }`. Native waits
  * for completion before OpenConnect calls connect(2).
  */
export declare function registerSocketProtect(callbacks: object): void

export declare function render(helper: object, slot: NodeContent): void

export declare function securePrivateFile(path: string): void

export declare function setPlatformVpnFailed(error: string): void

export declare function setPlatformVpnRunning(running: boolean): void

export declare function setPlatformVpnStarting(starting: boolean): void

export declare function startVpn(fd: number, optionsJson: string): Promise<void>

export declare function stopVpn(): Promise<void>

/** Submit answers for the current OpenConnect auth challenge (multi-round MFA). */
export declare function submitAuthChallenge(replyJson: string): void

export declare function syncPlatformChanges(): void

export declare function waitForPlatformChange(timeoutMs: number): Promise<boolean>

